version: '3'

volumes:
  back-data:

networks:
  back:
    name: back
    driver: bridge

services:
  proxy:
    container_name: proxy.cms.kaizen.com
    image: nginx:stable
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - '80:80'
      - '443:443'
    networks:
      - back

  frontend:
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./front/src:/app/src
      - ./front/public:/app/public
      # - ./ssl:/etc/ssl
    command: npm run start
    networks:
      - back


  back:
    container_name: back
    build:
      context: ./cms
      dockerfile: Dockerfile
    image: back:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: backDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./cms/config:/opt/app/config
      - ./cms/src:/opt/app/src
      - ./cms/package.json:/opt/package.json
      - ./cms/package-lock.json:/opt/package-lock.json
      - ./cms/.env:/opt/app/.env
      - ./cms/public/uploads:/opt/app/public/uploads
    ports:
      - '9337:9337'
    networks:
      - back
    depends_on:
      - backDB
      
  backDB:
    container_name: backDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: mariadb:latest
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - back-data:/var/lib/mysql
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder
    ports:
      - '3306:3306'
    networks:
      - back
      
  # backAdminer:
  #   container_name: backAdminer
  #   image: adminer
  #   restart: unless-stopped
  #   ports:
  #     - '9090:8080'
  #   environment:
  #     - ADMINER_DEFAULT_SERVER=backDB
  #   networks:
  #     - back
  #   depends_on:
  #     - backDB

