version: '3'

volumes:
  html:
  dhparam:
  vhost:
  certs:
  conf:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge

services:
  proxy:
    container_name: proxy.localhost
    image: nginx:stable
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.local:/etc/nginx/conf.d
      # generate self signed certs for local development
      - ./nginx/certs:/etc/nginx/certs/:ro
    networks:
      - strapi

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: true
    ports:
      - '3000:3000'
    volumes:
      - ./front/src:/app/src
      - ./front/public:/app/public
    command: npm run start
    networks:
      - strapi

  strapi:
    container_name: strapi
    build: .
    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_HOST: strapiDB
    volumes:
      - ./strapi/config:/opt/app/config
      - ./strapi/src:/opt/app/src
      - ./strapi/package.json:/opt/package.json
      - ./strapi/package-lock.json:/opt/package-lock.json

      - ./.env:/opt/app/.env
      - ./strapi/public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    networks:
      - strapi
    depends_on:
      - strapiDB
      
  strapiDB:
    container_name: strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/mysql
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder
    ports:
      - '3306:3306'
    networks:
      - strapi
      
  strapiAdminer:
    container_name: strapiAdminer
    image: adminer
    restart: unless-stopped
    ports:
      - '9090:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=strapiDB
    networks:
      - strapi
    depends_on:
      - strapiDB
